export type SourceCoverage = 'Hoog' | 'Gemiddeld' | 'Beperkt';

export interface ActivitySource {
  id: string;
  name: string;
  website: string;
  activityUrl: string;
  model: string;
  coverage: SourceCoverage;
  area: string;
  freshness: string;
  activityCount: string;
  categories: string[];
  summary: string;
  examples: string[];
  note?: string;
}

// This is an editorial source inventory, based on the public Den Haag pages
// reviewed on 19 August 2026. It intentionally separates live listings from
// evergreen editorial inspiration so visitors can judge how time-sensitive a
// result is before relying on it.
export const DEN_HAAG_ACTIVITY_SOURCES: ActivitySource[] = [
  {
    id: 'getyourguide',
    name: 'GetYourGuide',
    website: 'https://www.getyourguide.com',
    activityUrl: 'https://www.getyourguide.com/en-gb/the-hague-l1267/',
    model: 'Boekbare tours & tickets',
    coverage: 'Hoog',
    area: 'Den Haag en Scheveningen',
    freshness: 'Dynamische beschikbaarheid en datumfilters',
    activityCount: '116 resultaten op de Haagse bestemmingpagina',
    categories: ['Tours', 'Musea', 'Rondvaarten', 'Gezin', 'Fietsen'],
    summary: 'Internationale boekingsmarktplaats met direct boekbare Haagse tours, entreebewijzen en experiences.',
    examples: ['Grachtenrondvaart', 'Mauritshuis-ticket', 'Madurodam'],
  },
  {
    id: 'denhaag-com',
    name: 'DenHaag.com',
    website: 'https://denhaag.com',
    activityUrl: 'https://denhaag.com/en/calendar',
    model: 'Officiële stadsagenda',
    coverage: 'Hoog',
    area: 'Den Haag, Scheveningen, Kijkduin en wijken',
    freshness: 'Live agenda met datum-, wijk- en toegankelijkheidsfilters',
    activityCount: 'Doorlopende agenda',
    categories: ['Festivals', 'Muziek', 'Cultuur', 'Markten', 'Sport', 'Workshops'],
    summary: 'De officiële bezoekersagenda van de stad met de breedste lokale dekking en bruikbare filters.',
    examples: ['Festival', 'Tentoonstelling', 'Workshop'],
  },
  {
    id: 'wearetravelers',
    name: 'We Are Travelers',
    website: 'https://www.wearetravelers.nl',
    activityUrl: 'https://www.wearetravelers.nl',
    model: 'Reisinspiratie',
    coverage: 'Beperkt',
    area: 'Nederland, geen aparte actuele Haagse index aangetroffen',
    freshness: 'Redactioneel; datum per artikel controleren',
    activityCount: 'Geen Haagse activiteitenindex bevestigd',
    categories: ['Stedentrip', 'Inspiratie'],
    summary: 'Landelijk reismagazine dat vooral als aanvullende inspiratiebron kan dienen.',
    examples: ['Reisverhalen', 'Stedentriptips'],
    note: 'Niet als primaire bron voor actuele Haagse activiteiten inzetten.',
  },
  {
    id: 'flitz-events',
    name: 'Flitz-Events',
    website: 'https://flitz-events.nl',
    activityUrl: 'https://flitz-events.nl/teamuitje/den-haag',
    model: 'Boekbare groepsactiviteiten',
    coverage: 'Hoog',
    area: 'Den Haag, centrum en strand',
    freshness: 'Doorlopend aanbod, op aanvraag boekbaar',
    activityCount: '63 buitenactiviteiten en 27 strandactiviteiten genoemd',
    categories: ['Teamuitjes', 'Strand', 'City games', 'Rondvaart', 'Creatief'],
    summary: 'Aanbieder van bedrijfs-, familie- en groepsuitjes met veel maatwerk in Den Haag.',
    examples: ['Rondvaart', 'Robinson Crusoe', 'Borrelboot'],
  },
  {
    id: 'tripadvisor',
    name: 'Tripadvisor',
    website: 'https://www.tripadvisor.nl',
    activityUrl: 'https://www.tripadvisor.nl/Attractions-g188633-Activities-The_Hague_South_Holland_Province.html',
    model: 'Reviewgedreven attractiegids',
    coverage: 'Hoog',
    area: 'Den Haag',
    freshness: 'Doorlopende rangschikking op reviews',
    activityCount: 'Top-attracties en individuele locaties',
    categories: ['Musea', 'Attracties', 'Tours', 'Bezienswaardigheden'],
    summary: 'Vergelijkingsbron voor populaire Haagse attracties, met reviews als belangrijk selectiesignaal.',
    examples: ['Museon-Omniversum', 'Kunstmuseum', 'Louwman Museum'],
  },
  {
    id: 'kidsproof',
    name: 'Kidsproof Den Haag',
    website: 'https://www.kidsproof.nl',
    activityUrl: 'https://www.kidsproof.nl/denhaag/uitjes/uitagenda/',
    model: 'Gezinsagenda & tips',
    coverage: 'Hoog',
    area: 'Regio Den Haag, Delft en Zoetermeer',
    freshness: 'Actuele agenda en seizoenspagina’s',
    activityCount: 'Doorlopende uitagenda',
    categories: ['Kinderen', 'Festivals', 'Sport', 'Musea', 'Vakantie'],
    summary: 'Sterke lokale bron voor gezinnen, met activiteiten voor vandaag, weekend en schoolvakanties.',
    examples: ['Kinderfestival', 'Sportzomer', 'Scheveningen-uitje'],
  },
  {
    id: 'reisroutes',
    name: 'Reisroutes',
    website: 'https://www.reisroutes.nl',
    activityUrl: 'https://www.reisroutes.nl/stadswandelingen/den-haag/',
    model: 'Routes & reisgidsen',
    coverage: 'Hoog',
    area: 'Den Haag, Scheveningen en Zuid-Holland',
    freshness: 'Evergreen routes; evenementdata controleren',
    activityCount: '2 Haagse stadswandelingen en aanvullende routes',
    categories: ['Wandelen', 'Fietsen', 'Bezienswaardigheden', 'Stedentrip'],
    summary: 'Routegerichte inspiratie met downloads, kaarten en stadswandelingen voor zelfstandige ontdekking.',
    examples: ['Stadswandeling', 'Kerstmarktwandeling', 'Fietsroute richting Delft'],
  },
  {
    id: 'follow-my-footprints',
    name: 'Follow my footprints',
    website: 'https://www.followmyfootprints.nl',
    activityUrl: 'https://www.followmyfootprints.nl/category/nederland/den-haag/',
    model: 'Lokale redactionele gids',
    coverage: 'Hoog',
    area: 'Den Haag, Scheveningen en Kijkduin',
    freshness: 'Artikelen; publicatie- en eventdata controleren',
    activityCount: 'Haagse categoriepagina met doorlopende artikelen',
    categories: ['Lokale tips', 'Food tours', 'Festivals', 'Strand', 'Cultuur'],
    summary: 'Lokale, persoonlijke tips met nadruk op wijken, weekendideeën en Haagse belevenissen.',
    examples: ['Food tour', 'Paleis Noordeinde', 'Weekend in Scheveningen'],
  },
  {
    id: 'dagjeweg',
    name: 'DagjeWeg.NL',
    website: 'https://www.dagjeweg.nl',
    activityUrl: 'https://www.dagjeweg.nl/dagjeuit/den-haag/stedentrips',
    model: 'Uitjesdatabase & redactie',
    coverage: 'Hoog',
    area: 'Den Haag en omgeving',
    freshness: 'Locatiepagina’s plus nieuws en arrangementen',
    activityCount: 'Doorlopende locatie- en dagtripindex',
    categories: ['Attracties', 'City games', 'Musea', 'Rondleidingen', 'Stedentrips'],
    summary: 'Breed uitjesplatform met individuele attracties, redactionele selecties en city games.',
    examples: ['Escape the City', 'Madurodam', 'Tweede Kamer-rondleiding'],
  },
  {
    id: 'eventbrite',
    name: 'Eventbrite',
    website: 'https://www.eventbrite.nl',
    activityUrl: 'https://www.eventbrite.nl/d/netherlands--the-hague/events/',
    model: 'Ticketed evenementenagenda',
    coverage: 'Hoog',
    area: 'Den Haag en nabije regio',
    freshness: 'Live, datum- en prijsfilterbaar',
    activityCount: 'Doorlopende agenda',
    categories: ['Muziek', 'Tours', 'Community', 'Gratis', 'Workshops'],
    summary: 'Platform voor actuele, ticketbare en gratis evenementen met organisatorinformatie.',
    examples: ['KM@NIGHT', 'Walking tour', 'Concert'],
  },
  {
    id: 'fijnuit',
    name: 'FijnUit',
    website: 'https://www.fijnuit.nl',
    activityUrl: 'https://www.fijnuit.nl/den-haag',
    model: 'Uitjesdirectory',
    coverage: 'Hoog',
    area: 'Den Haag en omgeving',
    freshness: 'Doorlopende locatiepagina’s; aanbiedingen apart markeren',
    activityCount: 'Doorlopende index per activiteitstype',
    categories: ['Musea', 'Wellness', 'Routes', 'Games', 'Gezin'],
    summary: 'Uitjeszoeker met categoriepagina’s, locaties en eventuele voordeelmeldingen.',
    examples: ['Museon-Omniversum', 'City Trail', 'Outside Escape'],
  },
  {
    id: 'wattedoenin',
    name: 'Wat te doen in',
    website: 'https://www.wattedoenin.nl',
    activityUrl: 'https://www.wattedoenin.nl/wat-te-doen-in/den-haag/',
    model: 'Stadsgids & locatieagenda',
    coverage: 'Hoog',
    area: 'Den Haag en Scheveningen',
    freshness: 'Locatieagenda’s en artikelen; individuele data controleren',
    activityCount: '26 Haagse uitjes in de stadsgids',
    categories: ['Bezienswaardigheden', 'Musea', 'Evenementen', 'Gezin', 'Koninklijk'],
    summary: 'Toegankelijke stadsgids die vaste highlights combineert met locatie- en evenementpagina’s.',
    examples: ['Madurodam', 'Muzee Scheveningen', 'Museumnacht'],
  },
  {
    id: 'travel-around-with-me',
    name: 'Travel Around With Me',
    website: 'https://www.travelaroundwithme.com',
    activityUrl: 'https://www.travelaroundwithme.com/gratis-doen-den-haag/',
    model: 'Lokale reisinspiratie',
    coverage: 'Hoog',
    area: 'Den Haag, Binckhorst, Scheveningen en natuurgebieden',
    freshness: 'Redactioneel; data bij evenementen verifiëren',
    activityCount: 'Meerdere Haagse gidsartikelen',
    categories: ['Gratis', 'Wandelen', 'Street art', 'Weekend', 'Natuur'],
    summary: 'Persoonlijke Haagse inspiratie met nadruk op gratis opties, wandelen en onverwachte plekken.',
    examples: ['Hofjeswandeling', 'Street-art route', 'Gratis cultuur'],
  },
  {
    id: 'yellowbrick',
    name: 'Yellowbrick',
    website: 'https://yellowbrick.nl',
    activityUrl: 'https://yellowbrick.nl/blog/wat-te-doen-in-den-haag-tips-and-uitagenda/',
    model: 'Bezoekplanning & inspiratie',
    coverage: 'Beperkt',
    area: 'Den Haag, vooral centrumbezoek',
    freshness: 'Redactioneel; geen zelfstandige activiteitenfeed',
    activityCount: 'Eén Haagse inspiratiegids bevestigd',
    categories: ['Bezienswaardigheden', 'Musea', 'Winkelen', 'Parkeren'],
    summary: 'Parkeerdienst met een aanvullende Haagse inspiratiegids; bruikbaar voor bezoeklogistiek, niet voor een actuele agenda.',
    examples: ['Musea', 'Centrumbezoek', 'Parkeertips'],
    note: 'Alleen als ondersteunende bezoekinformatie tonen.',
  },
  {
    id: 'wannado',
    name: 'Wannado',
    website: 'https://wannado.nl',
    activityUrl: 'https://wannado.nl/wat-te-doen/den-haag/categorie/activiteiten-uitjes',
    model: 'Uitjeszoeker & agenda',
    coverage: 'Hoog',
    area: 'Den Haag en omgeving',
    freshness: 'Dynamische openingstijden, agenda en prijsfilters',
    activityCount: '65 uitjes in de Haagse categorie',
    categories: ['Musea', 'Escape rooms', 'Muziek', 'Routes', 'VR'],
    summary: 'Goed gestructureerde activiteitenzoeker met reviewscore, openingstijden, prijs en filters.',
    examples: ['Mauritshuis', 'Concertagenda', 'Escape room'],
  },
  {
    id: 'see-the-hague',
    name: 'seeTheHague',
    website: 'https://seethehague.nl',
    activityUrl: 'https://seethehague.nl/activiteiten-in-den-haag/',
    model: 'Lokale rondleidingen',
    coverage: 'Hoog',
    area: 'Den Haag',
    freshness: 'Boekbare tours op vaste of aanvraagbasis',
    activityCount: 'Meerdere fiets- en wandeltours',
    categories: ['Wandelen', 'Fietsen', 'Privétours', 'Highlights'],
    summary: 'Lokale gids voor begeleide fiets- en wandeltours door de stad.',
    examples: ['Highlights-fietstour', 'Privé-wandeltour', 'Stadswandeling'],
  },
  {
    id: 'stappen-in-den-haag',
    name: 'Stappen in Den Haag',
    website: 'https://stappenindenhaag.nl',
    activityUrl: 'https://stappenindenhaag.nl/de-uitagenda-van-den-haag/',
    model: 'Lokale uitagenda & nieuws',
    coverage: 'Hoog',
    area: 'Den Haag',
    freshness: 'Agenda- en nieuwsstroom; datum per item controleren',
    activityCount: 'Doorlopende uitagenda',
    categories: ['Uitgaan', 'Muziek', 'Nachtleven', 'Tours', 'Nieuws'],
    summary: 'Haagse uitgaans- en nieuwssite met een lokale agenda en stadsgerichte verhalen.',
    examples: ['Rock History Tour', 'Haagse highlights', 'Uitgaansagenda'],
  },
  {
    id: 'weekends-in',
    name: 'Weekends in',
    website: 'https://week-endsin.com',
    activityUrl: 'https://week-endsin.com/the-hague/activities/',
    model: 'Engelstalige stadsgids',
    coverage: 'Gemiddeld',
    area: 'Den Haag en wijken',
    freshness: 'Redactioneel; geen expliciet live agendamodel bevestigd',
    activityCount: '20 dingen om te doen en wijkpagina’s',
    categories: ['Highlights', 'Wijken', 'Cultuur', 'Food', 'Weekend'],
    summary: 'Engelstalige gids voor bezoekers die Haagse activiteiten per buurt en thema willen verkennen.',
    examples: ['Zeeheldenkwartier', 'Lange Voorhout', 'City highlights'],
  },
  {
    id: 'mooiste-stedentrips',
    name: 'Mooiste Stedentrips',
    website: 'https://mooistestedentrips.nl',
    activityUrl: 'https://mooistestedentrips.nl/mini-break-in-nederland-den-haag/',
    model: 'Stedentrip-inspiratie',
    coverage: 'Gemiddeld',
    area: 'Den Haag',
    freshness: 'Evergreen artikel; actuele informatie verifiëren',
    activityCount: '17 Haagse bezienswaardigheden in een gids',
    categories: ['Stedentrip', 'Bezienswaardigheden', 'Cultuur', 'Weekend'],
    summary: 'Compacte stedentripgids voor vaste Haagse highlights en tripplanning.',
    examples: ['Musea', 'Historisch centrum', 'Stedentriproute'],
  },
  {
    id: '1001activiteiten',
    name: '1001activiteiten',
    website: 'https://www.1001activiteiten.nl',
    activityUrl: 'https://www.1001activiteiten.nl/provincie-zuid-holland/den-haag',
    model: 'Boekbare uitjesdatabase',
    coverage: 'Hoog',
    area: 'Den Haag',
    freshness: 'Doorlopende aanbieder- en arrangementenindex',
    activityCount: '700+ mogelijkheden op de Haagse pagina',
    categories: ['Workshops', 'Teambuilding', 'Spel', 'Creatief', 'Arrangementen'],
    summary: 'Groot aanbod van originele en boekbare groepsactiviteiten met thematische filters.',
    examples: ['Circusworkshop', 'Nieuwe uitjes', 'Arrangement'],
  },
  {
    id: 'uitjes-nl',
    name: 'Uitjes.nl',
    website: 'https://uitjes.nl',
    activityUrl: 'https://uitjes.nl/den-haag-uitjes/',
    model: 'Uitjesdirectory',
    coverage: 'Hoog',
    area: 'Den Haag',
    freshness: 'Doorlopende locatie- en activiteitspagina’s',
    activityCount: 'Doorlopende Haagse categoriepagina',
    categories: ['Musea', 'Speurtochten', 'Wandelen', 'Spellen', 'Actief'],
    summary: 'Landelijke uitjesgids met Haagse locatiepagina’s en individuele activiteiten.',
    examples: ['Escher in Het Paleis', 'Mauritshuis', 'E-speurtocht'],
  },
  {
    id: 'enter-the-hague',
    name: 'Enter The Hague',
    website: 'https://www.enterthehague.com',
    activityUrl: 'https://www.enterthehague.com/the-hague-free-walking-tour',
    model: 'Begeleide stadstours',
    coverage: 'Hoog',
    area: 'Den Haag centrum',
    freshness: 'Boekbare tours en redactionele tips',
    activityCount: 'Meerdere rondleidingen plus bezoekersgids',
    categories: ['Gratis tours', 'Wandelen', 'Verborgen plekken', 'Highlights'],
    summary: 'Engelstalige aanbieder van stadswandelingen, waaronder een gratis tour door het centrum.',
    examples: ['Free walking tour', 'Highlights', 'Verborgen plekken'],
  },
  {
    id: 'cultuurschakel',
    name: 'CultuurSchakel',
    website: 'https://www.cultuurschakel.nl',
    activityUrl: 'https://www.cultuurschakel.nl/vrije-tijd/cultuur-proeven/',
    model: 'Cultureel aanbodnetwerk',
    coverage: 'Gemiddeld',
    area: 'Den Haag',
    freshness: 'Aanbieders- en cultuurprogramma’s; programma per partij controleren',
    activityCount: 'Meerdere Haagse culturele aanbieders',
    categories: ['Kunst', 'Cultuur', 'Workshops', 'Podium', 'Participatie'],
    summary: 'Haags netwerk voor kunst en cultuur, waardevol voor lokaal cultuurparticipatie-aanbod.',
    examples: ['Mauritshuis', 'Museon-Omniversum', 'Korzo'],
  },
  {
    id: 'lekkerweg',
    name: 'Lekkerweg Tips',
    website: 'https://www.lekkerwegtips.nl',
    activityUrl: 'https://www.lekkerwegtips.nl/wat-te-doen-in-den-haag/',
    model: 'Reisinspiratie',
    coverage: 'Gemiddeld',
    area: 'Den Haag en Zuid-Holland',
    freshness: 'Redactioneel; artikel is uit 2024',
    activityCount: '16 Haagse tips in de bevestigde gids',
    categories: ['Bezienswaardigheden', 'Musea', 'Stedentrip', 'Kust'],
    summary: 'Inspiratieblog voor vaste Haagse highlights en een bezoek aan de stad of kust.',
    examples: ['Binnenhof', 'Vredespaleis', 'Mauritshuis'],
    note: 'Gebruik als evergreen inspiratie, niet als actuele agenda.',
  },
];